(define (expert b n)
  (define (even? count max-count)
    (cond ((> (* count 2) max-count) 0)
	  (else 1)))
  (define (fast-expert b product count max-count)
    (cond ((= count max-count) product)
	  ((even? count max-count) (fast-expert b (* product product) (* 2 count) max-count))
	  (else (fast-expert (* product b) (+ count 1) max-count))))
  (fast-expert b b 1 n))
