(define (prime? n)
  (define (divides? a b)
    (= (remainder b a) 0))
  (define (squre a) (* a a))
  (define (find-divisor n test-divisor)
    (cond ((> (squre test-divisor) n) n)
	  ((divides? test-divisor n) test-divisor)
	  (else (find-divisor n (+ test-divisor 1)))))
  (define (smallest-divisor n)
    (find-divisor n 2))
  (= n (smallest-divisor n)))