(define (check-odd-prime n)
  (define (report-prime elapsed-time n)
    (display " *** ")
    (display n)
    (newline)
    (display elapsed-time))
  (define (start-prime-test n start-time)
    (cond ((prime? n) (report-prime (- (runtime) start-time) n))
	  (else (start-prime-test (+ 1 n) start-time))))
  (define (timed-prime-test n)
    (newline)
    (display n)
    (start-prime-test n (runtime)))
  (timed-prime-test n))
