(define (sum term a next b)
  (if (> a b)
      0
      (+ (term b)
	 (sum term (next a) next b))))
(define (f x) (* x x x))
(define (integral1 f a b dx)
  (define (add-dx) (+ x dx))
  (* (sum f (+ a (/ dx 2.0)) add-dx b)
     dx))
