(define (make-point x y)
  (cons x y))
(define (x-point point)
  (car point))
(define (y-point point)
  (cdr point))
(define (make-segment point1 point2)
  (cons point1 point2))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))
(define (mid-point segment)
  (make-segment (/ (+ (car (car segment)) (car (cdr segment))) 2) (/ (+ (cdr (car segment)) (cdr (cdr segment))) 2)))
(define (print segemnt)
  (newline)
  (display (car z))
  (newline)
  (display (cdr z)))
