(define (make-interval lower upper)
  (cons lower upper))
(define (print-interval interval)
  (newline)
  (display (car interval))
  (newline)
  (display (cdr interval)))
(define (sub-interval int1 int2)
  (make-interval  (cond ((> (car int1) (car int2))
			      (car int2))
			     (else (car int1)))
		       (cond ((> (cdr int1) (cdr int2))
			     (cdr int2))
			     (else (cdr int1)))))
